### ISSUE TITLE
[DOCS] 404 link on Memory Quickstart

### ISSUE THREAD

**Issue by johanguse** [LangbaseInc/BaseAI#31]
### Description

404 link on Docs page.
I found a 404 link on this page https://baseai.dev/docs/memory/quickstart at the link `Create a memory in BaseAI.`

I can't find the documentation repository. It would be a good idea to make it public so anyone can contribute to fixing errors.

**Comment by msaaddev** [comment]
Thanks for reporting @johanguse! I have fixed the broken link.

The documentation site code is also public and is available inside [apps/baseai.dev](https://github.com/LangbaseInc/BaseAI/tree/main/apps/baseai.dev) in this repo. Feel free to send a PR if you find any other broken links in the docs.

Closing this issue since this has been fixed.
